[book]
authors = ["mythter"]
src = "src"
title = "mura"

[output.html]
git-repository-url = "https://github.com/mythter/mura"
edit-url-template = "https://github.com/mythter/mura/edit/main/{path}"
additional-css = [
  "theme/css/language-picker.css",
]

[output.html.fold]
enable = true
level = 1

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]
