[book]
authors = ["mythter"]
language = "en"
multilingual = false
src = "src"
title = "mura"

[output.html]
git-repository-url = "https://github.com/mythter/mura"
edit-url-template = "https://github.com/mythter/mura/edit/main/{path}"